Melakukan import terhadap library yang dibutuhkan dalam kegiatan analisis data.

In [134]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

Loading Data Dan Melihat Data yang ingin Di analisis

In [135]:
df = pd.read_csv('/content/drive/MyDrive/Dataset_Collab/loan_data_2007_2014.csv', low_memory=False)
pd.set_option('display.max_columns', None)
df.head(5)

Unnamed: 0       id  member_id  loan_amnt  funded_amnt  funded_amnt_inv  \
0           0  1077501    1296599       5000         5000           4975.0   
1           1  1077430    1314167       2500         2500           2500.0   
2           2  1077175    1313524       2400         2400           2400.0   
3           3  1076863    1277178      10000        10000          10000.0   
4           4  1075358    1311748       3000         3000           3000.0   

         term  int_rate  installment grade sub_grade  \
0   36 months     10.65       162.87     B        B2   
1   60 months     15.27        59.83     C        C4   
2   36 months     15.96        84.33     C        C5   
3   36 months     13.49       339.31     C        C1   
4   60 months     12.69        67.79     B        B5   

                  emp_title emp_length home_ownership  annual_inc  \
0                       NaN  10+ years           RENT     24000.0   
1                     Ryder   < 1 year           RENT     30000.0   
2                       NaN  10+ years           RENT     12252.0   
3       AIR RESOURCES BOARD  10+ years           RENT     49200.0   
4  University Medical Group     1 year           RENT     80000.0   

  verification_status issue_d  loan_status pymnt_plan  \
0            Verified  Dec-11   Fully Paid          n   
1     Source Verified  Dec-11  Charged Off          n   
2        Not Verified  Dec-11   Fully Paid          n   
3     Source Verified  Dec-11   Fully Paid          n   
4     Source Verified  Dec-11      Current          n   

                                                 url  \
0  https://www.lendingclub.com/browse/loanDetail....   
1  https://www.lendingclub.com/browse/loanDetail....   
2  https://www.lendingclub.com/browse/loanDetail....   
3  https://www.lendingclub.com/browse/loanDetail....   
4  https://www.lendingclub.com/browse/loanDetail....   

                                                desc         purpose  \
0    Borrower added on 12/22/11 > I need to upgra...     credit_card   
1    Borrower added on 12/22/11 > I plan to use t...             car   
2                                                NaN  small_business   
3    Borrower added on 12/21/11 > to pay for prop...           other   
4    Borrower added on 12/21/11 > I plan on combi...           other   

                  title zip_code addr_state    dti  delinq_2yrs  \
0              Computer    860xx         AZ  27.65          0.0   
1                  bike    309xx         GA   1.00          0.0   
2  real estate business    606xx         IL   8.72          0.0   
3              personel    917xx         CA  20.00          0.0   
4              Personal    972xx         OR  17.94          0.0   

  earliest_cr_line  inq_last_6mths  mths_since_last_delinq  \
0           Jan-85             1.0                     NaN   
1           Apr-99             5.0                     NaN   
2           Nov-01             2.0                     NaN   
3           Feb-96             1.0                    35.0   
4           Jan-96             0.0                    38.0   

   mths_since_last_record  open_acc  pub_rec  revol_bal  revol_util  \
0                     NaN       3.0      0.0      13648        83.7   
1                     NaN       3.0      0.0       1687         9.4   
2                     NaN       2.0      0.0       2956        98.5   
3                     NaN      10.0      0.0       5598        21.0   
4                     NaN      15.0      0.0      27783        53.9   

   total_acc initial_list_status  out_prncp  out_prncp_inv   total_pymnt  \
0        9.0                   f        0.0            0.0   5861.071414   
1        4.0                   f        0.0            0.0   1008.710000   
2       10.0                   f        0.0            0.0   3003.653644   
3       37.0                   f        0.0            0.0  12226.302210   
4       38.0                   f      766.9          766.9   3242.170000   

   total_

melihat info yang ada didalam dataset dan melihat kelengkapan dan jumlah kolom yang ada pada dataset.

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 75 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   Unnamed: 0                   466285 non-null  int64  
 1   id                           466285 non-null  int64  
 2   member_id                    466285 non-null  int64  
 3   loan_amnt                    466285 non-null  int64  
 4   funded_amnt                  466285 non-null  int64  
 5   funded_amnt_inv              466285 non-null  float64
 6   term                         466285 non-null  object 
 7   int_rate                     466285 non-null  float64
 8   installment                  466285 non-null  float64
 9   grade                        466285 non-null  object 
 10  sub_grade                    466285 non-null  object 
 11  emp_title                    438697 non-null  object 
 12  emp_length                   445277 non-null  object 
 13 

menghapus fitur-fitur yang dianggap tidak berguna atau tidak diperlukan untuk analisis data saat ini dan menyimpan dataset hasil filter kedalam variable yang baru.

In [137]:
df_drop =[0,1,2,11,19,20,24,29,30,48,51,54,55,56,60,61,62,63,64,65,66,67,68,69,70,72,73,74]
df_filtered = df.drop(df.columns[df_drop],axis=1)
df_filtered.head()

loan_amnt  funded_amnt  funded_amnt_inv        term  int_rate  installment  \
0       5000         5000           4975.0   36 months     10.65       162.87   
1       2500         2500           2500.0   60 months     15.27        59.83   
2       2400         2400           2400.0   36 months     15.96        84.33   
3      10000        10000          10000.0   36 months     13.49       339.31   
4       3000         3000           3000.0   60 months     12.69        67.79   

  grade sub_grade emp_length home_ownership  annual_inc verification_status  \
0     B        B2  10+ years           RENT     24000.0            Verified   
1     C        C4   < 1 year           RENT     30000.0     Source Verified   
2     C        C5  10+ years           RENT     12252.0        Not Verified   
3     C        C1  10+ years           RENT     49200.0     Source Verified   
4     B        B5     1 year           RENT     80000.0     Source Verified   

  issue_d  loan_status pymnt_plan         purpose                 title  \
0  Dec-11   Fully Paid          n     credit_card              Computer   
1  Dec-11  Charged Off          n             car                  bike   
2  Dec-11   Fully Paid          n  small_business  real estate business   
3  Dec-11   Fully Paid          n           other              personel   
4  Dec-11      Current          n           other              Personal   

  zip_code    dti  delinq_2yrs earliest_cr_line  inq_last_6mths  open_acc  \
0    860xx  27.65          0.0           Jan-85             1.0       3.0   
1    309xx   1.00          0.0           Apr-99             5.0       3.0   
2    606xx   8.72          0.0           Nov-01             2.0       2.0   
3    917xx  20.00          0.0           Feb-96             1.0      10.0   
4    972xx  17.94          0.0           Jan-96             0.0      15.0   

   pub_rec  revol_bal  revol_util  total_acc initial_list_status  out_prncp  \
0      0.0      13648        83.7        9.0                   f        0.0   
1      0.0       1687         9.4        4.0                   f        0.0   
2      0.0       2956        98.5       10.0                   f        0.0   
3      0.0       5598        21.0       37.0                   f        0.0   
4      0.0      27783        53.9       38.0                   f      766.9   

   out_prncp_inv   total_pymnt  total_pymnt_inv  total_rec_prncp  \
0            0.0   5861.071414          5831.78          5000.00   
1            0.0   1008.710000          1008.71           456.46   
2            0.0   3003.653644          3003.65          2400.00   
3            0.0  12226.302210         12226.30         10000.00   
4          766.9   3242.170000          3242.17          2233.10   

   total_rec_int  total_rec_late_fee  recoveries  collection_recovery_fee  \
0         861.07                0.00        0.00                     0.00   
1         435.17                0.00      117.08                     1.11   
2         603.65                0.00        0.00                     0.00   
3        2209.33               16.97        0.00                     0.00   
4        1009.07                0.00        0.00                     0.00   

  last_pymnt_d  last_pymnt_amnt last_credit_pull_d  \
0       Jan-15           171.62             Jan-16   
1       Apr-13           119.66             Sep-13   
2       Jun-14           649.91             Jan-16   
3       Jan-15           357.48             Jan-15   
4       Jan-16            67.79             Jan-16   

   collections_12_mths_ex_med  policy_code application_type  acc_now_delinq  \
0                         0.0            1       INDIVIDUAL             0.0   
1                         0.0            1       INDIVIDUAL             0.0   
2                         0.0            1       INDIVIDUAL             0.0   
3                         0.0            1       INDIVIDUAL             0.0   
4                         0.0            1       INDIVIDUAL 

In [138]:
df_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 47 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   loan_amnt                   466285 non-null  int64  
 1   funded_amnt                 466285 non-null  int64  
 2   funded_amnt_inv             466285 non-null  float64
 3   term                        466285 non-null  object 
 4   int_rate                    466285 non-null  float64
 5   installment                 466285 non-null  float64
 6   grade                       466285 non-null  object 
 7   sub_grade                   466285 non-null  object 
 8   emp_length                  445277 non-null  object 
 9   home_ownership              466285 non-null  object 
 10  annual_inc                  466281 non-null  float64
 11  verification_status         466285 non-null  object 
 12  issue_d                     466285 non-null  object 
 13  loan_status   

Melihat nilai unik yang ada didalam feature loan_Status yang akan di jadikan label dalam analisis kali ini.

In [139]:
df_filtered['loan_status'].unique()

array(['Fully Paid', 'Charged Off', 'Current', 'Default',
       'Late (31-120 days)', 'In Grace Period', 'Late (16-30 days)',
       'Does not meet the credit policy. Status:Fully Paid',
       'Does not meet the credit policy. Status:Charged Off'],
      dtype=object)

Kemudian kmai merename kolom kolom yang ada agar kolom lebih mudah untuk dimengerti

In [140]:
df_ubah = df_filtered.rename(columns={'loan_amnt':'pinjaman_diterima_bLalu','funded_amnt':'pinjaman_disetujui','term':'tenor_pinjaman',
                             'installment':'pembayaran_bulanan','emp_length':'lama_bekerja','home_ownership':'kepemilikan_properti','annual_inc':'pendapatan_tahunan',
                             'verification_status':'status_verifikasi','issue_d':'bulan_pinjaman_diberikan','loan_status':'status_pinjaman',
                             'purpose':'tujuan_pinjaman','title':'nama_pinjaman','delinq_2yrs':'keterlambatan_2thn','dti':'rasio_bayar_bulanan',
                             'earliest_cr_line':'bulan_pembukaan_rekening','inq_last_6mths':'pertanyaan_cr_6bln','open_acc':'akun_kredit_aktif',
                             'pub_rec':'catatan_negatif_publik','revol_bal':'putaran_saldo','revol_util':'rasio_penggunaan_saldo','total_acc':'total_akun_kredit',
                             'initial_list_status':'status_penawaran_pinjaman','out_prncp':'sisa_pokok_pendanaan','out_prncp_inv':'sisa_pokok_pendanaan_inv',
                             'total_pymnt':'total_pembayaran','total_pymnt_inv':'total_pembayaran_inv','total_rec_prncp':'total_pokok_diterima',
                             'total_rec_int':'total_bunga','total_rec_late_fee':'total_bunga_terlambat','recoveries':'perlakuan_rencana_pembayaran',
                             'collection_recovery_fee':'biaya_charge_off','last_pymnt_d':'pembayaran_terakhir','last_pymnt_amnt':'jumlah_pembayaran_terakhir',
                             'total_rev_hi_lim':'limit_kredit_tertinggi','tot_cur_bal':'total_saldo_akun','tot_coll_amt':'total_hutang_tertunggak',
                              'last_credit_pull_d':'last_cek_hisKredit','collections_12_mths_ex_med':'usaha_penagihan_12bln','acc_now_delinq':'rekening_menunggak'})
df_ubah.head(5)

pinjaman_diterima_bLalu  pinjaman_disetujui  funded_amnt_inv  \
0                     5000                5000           4975.0   
1                     2500                2500           2500.0   
2                     2400                2400           2400.0   
3                    10000               10000          10000.0   
4                     3000                3000           3000.0   

  tenor_pinjaman  int_rate  pembayaran_bulanan grade sub_grade lama_bekerja  \
0      36 months     10.65              162.87     B        B2    10+ years   
1      60 months     15.27               59.83     C        C4     < 1 year   
2      36 months     15.96               84.33     C        C5    10+ years   
3      36 months     13.49              339.31     C        C1    10+ years   
4      60 months     12.69               67.79     B        B5       1 year   

  kepemilikan_properti  pendapatan_tahunan status_verifikasi  \
0                 RENT             24000.0          Verified   
1                 RENT             30000.0   Source Verified   
2                 RENT             12252.0      Not Verified   
3                 RENT             49200.0   Source Verified   
4                 RENT             80000.0   Source Verified   

  bulan_pinjaman_diberikan status_pinjaman pymnt_plan tujuan_pinjaman  \
0                   Dec-11      Fully Paid          n     credit_card   
1                   Dec-11     Charged Off          n             car   
2                   Dec-11      Fully Paid          n  small_business   
3                   Dec-11      Fully Paid          n           other   
4                   Dec-11         Current          n           other   

          nama_pinjaman zip_code  rasio_bayar_bulanan  keterlambatan_2thn  \
0              Computer    860xx                27.65                 0.0   
1                  bike    309xx                 1.00                 0.0   
2  real estate business    606xx                 8.72                 0.0   
3              personel    917xx                20.00                 0.0   
4              Personal    972xx                17.94                 0.0   

  bulan_pembukaan_rekening  pertanyaan_cr_6bln  akun_kredit_aktif  \
0                   Jan-85                 1.0                3.0   
1                   Apr-99                 5.0                3.0   
2                   Nov-01                 2.0                2.0   
3                   Feb-96                 1.0               10.0   
4                   Jan-96                 0.0               15.0   

   catatan_negatif_publik  putaran_saldo  rasio_penggunaan_saldo  \
0                     0.0          13648                    83.7   
1                     0.0           1687                     9.4   
2                     0.0           2956                    98.5   
3                     0.0           5598                    21.0   
4                     0.0          27783                    53.9   

   total_akun_kredit status_penawaran_pinjaman  sisa_pokok_pendanaan  \
0                9.0                         f                   0.0   
1                4.0                         f                   0.0   
2               10.0                         f                   0.0   
3               37.0                         f                   0.0   
4               38.0                         f                 766.9   

   sisa_pokok_pendanaan_inv  total_pembayaran  total_pembayaran_inv  \
0                       0.0       5861.071414               5831.78   
1                       0.0       1008.710000               1008.71   
2                       0.0       3003.653644               3003.65   
3                       0.0      12226.302210              12226.30   
4                     766.9       3242.170000               3242.17   

   total_pokok_diterima  total_bunga  total_bunga_terlambat  \
0               5000.00       861.07                   0.00   
1                456.46     

In [141]:
df_ubah = df_ubah.dropna(subset=['lama_bekerja'])
df_ubah['lama_bekerja'].isnull().sum()

0

In [142]:
df_ubah = df_ubah.dropna(subset=['limit_kredit_tertinggi'])
df_ubah['limit_kredit_tertinggi'].isnull().sum()

0

In [143]:
label_encoder = LabelEncoder()
df_ubah['lama_bekerja'] = label_encoder.fit_transform(df_ubah['lama_bekerja'])
df_ubah['status_verifikasi'] = label_encoder.fit_transform(df_ubah['status_verifikasi'])
df_ubah['kepemilikan_properti'] = label_encoder.fit_transform(df_ubah['kepemilikan_properti'])
df_ubah['grade'] = label_encoder.fit_transform(df_ubah['grade'])
df_ubah['status_pinjaman']=  label_encoder.fit_transform(df_ubah['status_pinjaman'])
df_ubah['pymnt_plan']=  label_encoder.fit_transform(df_ubah['pymnt_plan'])

In [144]:
df_ubah['zip_code'] = df_ubah['zip_code'].str.replace('xx', '')

## **Explanatory Data Analysis (EDA)**

In [145]:
X = df_ubah[['zip_code','lama_bekerja','policy_code','pendapatan_tahunan','grade','kepemilikan_properti','pinjaman_disetujui',
             'status_verifikasi','rekening_menunggak','keterlambatan_2thn','usaha_penagihan_12bln','catatan_negatif_publik',
             'total_hutang_tertunggak','perlakuan_rencana_pembayaran','pymnt_plan','akun_kredit_aktif','total_akun_kredit',
             'putaran_saldo']]
y = df_ubah[['status_pinjaman']]

In [146]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 377062 entries, 42535 to 466284
Data columns (total 18 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   zip_code                      377062 non-null  object 
 1   lama_bekerja                  377062 non-null  int64  
 2   policy_code                   377062 non-null  int64  
 3   pendapatan_tahunan            377062 non-null  float64
 4   grade                         377062 non-null  int64  
 5   kepemilikan_properti          377062 non-null  int64  
 6   pinjaman_disetujui            377062 non-null  int64  
 7   status_verifikasi             377062 non-null  int64  
 8   rekening_menunggak            377062 non-null  float64
 9   keterlambatan_2thn            377062 non-null  float64
 10  usaha_penagihan_12bln         377062 non-null  float64
 11  catatan_negatif_publik        377062 non-null  float64
 12  total_hutang_tertunggak       377062 non

In [147]:
y.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 377062 entries, 42535 to 466284
Data columns (total 1 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   status_pinjaman  377062 non-null  int64
dtypes: int64(1)
memory usage: 5.8 MB


In [148]:
X.head()

zip_code  lama_bekerja  policy_code  pendapatan_tahunan  grade  \
42535      481             1            1             55000.0      1   
42536      927             0            1             26000.0      2   
42537      060             1            1            105000.0      0   
42538      871             1            1             40000.0      1   
42539      334             2            1             63000.0      0   

       kepemilikan_properti  pinjaman_disetujui  status_verifikasi  \
42535                     4               27050                  2   
42536                     5                9750                  0   
42537                     1               12000                  0   
42538                     5               12000                  1   
42539                     1               15000                  0   

       rekening_menunggak  keterlambatan_2thn  usaha_penagihan_12bln  \
42535                 0.0                 0.0                    0.0   
42536                 0.0                 0.0                    0.0   
42537                 0.0                 0.0                    0.0   
42538                 0.0                 0.0                    0.0   
42539                 0.0                 0.0                    0.0   

       catatan_negatif_publik  total_hutang_tertunggak  \
42535                     0.0                      0.0   
42536                     0.0                      0.0   
42537                     0.0                      0.0   
42538                     2.0                  15386.0   
42539                     0.0                   1514.0   

       perlakuan_rencana_pembayaran  pymnt_plan  akun_kredit_aktif  \
42535                           0.0           0               14.0   
42536                           0.0           0               12.0   
42537                           0.0           0               12.0   
42538                           0.0           0                7.0   
42539                           0.0           0                8.0   

       total_akun_kredit  putaran_saldo  
42535               27.0          36638  
42536               28.0           7967  
42537               22.0          13168  
42538               32.0           5572  
42539               29.0          11431

In [149]:
y.head()

status_pinjaman
42535                1
42536                1
42537                1
42538                3
42539                1

## **Splitting Data**

In [173]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=123)

In [176]:
X_train.drop(columns=['status_pinjaman'],axis=1, inplace=True)


In [177]:
scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [178]:
X_train

array([[0.06955645, 0.1       , 0.        , ..., 0.27380952, 0.35064935,
        0.01161505],
       [0.37298387, 0.9       , 0.        , ..., 0.1547619 , 0.16883117,
        0.0031779 ],
       [0.22479839, 0.3       , 0.        , ..., 0.14285714, 0.17532468,
        0.00418413],
       ...,
       [0.80040323, 0.4       , 0.        , ..., 0.05952381, 0.05844156,
        0.001993  ],
       [0.0796371 , 0.1       , 0.        , ..., 0.21428571, 0.16233766,
        0.00354458],
       [0.84979839, 1.        , 0.        , ..., 0.28571429, 0.32467532,
        0.00814443]])

## **Modelling Data**

In [179]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import metrics

RF = RandomForestClassifier(n_estimators=25, random_state=42)
RF.fit(X_train, y_train)
ypred = RF.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test,ypred))

Accuracy: 0.5866019571962765


In [180]:
print("Random Forest Model")
print("-------------------------------------------------------------")
print("Precision:",metrics.precision_score(y_test,ypred,average='micro'))
print("Recall:",metrics.recall_score(y_test,ypred,average='micro'))
print("F Score:",metrics.f1_score(y_test,ypred,average='micro'))
print("Confusion Matrix:\n",metrics.confusion_matrix(y_test,ypred))
print (metrics.classification_report(y_test, ypred))
print("-------------------------------------------------------------")

Random Forest Model
-------------------------------------------------------------
Precision: 0.5866019571962765
Recall: 0.5866019571962765
F Score: 0.5866019571962765
Confusion Matrix:
 [[ 1570  1294     0   170     0     0     0]
 [    9 18389     0  2617     0     0     2]
 [    0    73     0     7     0     0     0]
 [    3 10328     0  2160     1     0     1]
 [    0   273     0    46     0     0     0]
 [    0   118     0    12     0     0     0]
 [    1   560     0    73     0     0     0]]
              precision    recall  f1-score   support

           0       0.99      0.52      0.68      3034
           1       0.59      0.87      0.71     21017
           2       0.00      0.00      0.00        80
           3       0.42      0.17      0.25     12493
           4       0.00      0.00      0.00       319
           5       0.00      0.00      0.00       130
           6       0.00      0.00      0.00       634

    accuracy                           0.59     37707
   macro a